ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS brand TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS warranty TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS key_features TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS specs JSONB NOT NULL DEFAULT '[]'::jsonb;